#!/usr/bin/env python

import threading
import os
import time

def doopen(t, fp):
    time.sleep(t)
    fh = os.open(fp, flags=os.O_RDONLY)
    print(fp, "was opened")
    time.sleep(t)
    os.close(fh)
    

t1 = threading.Thread(target=doopen, args=(1, "/tmp/movida1.txt"))
t2 = threading.Thread(target=doopen, args=(2, "/tmp/movida2.txt"))

t1.start()
t2.start()
t1.join()
t2.join()
