#!/usr/bin/python

import gc
import os
import sys

gc.disable()

try:
    remaining = int(sys.argv[1])
except IndexError:
    remaining = 1

for _ in range(remaining):
    if os.fork() == 0:
        break
